version: '3'

services:
  flask-service:
    build:
      context: .
      dockerfile: Dockerfile-flask
    ports:
      - "8080:5000"
    depends_on:
      - celery-service
      - kafka-service
      - zookeeper-service
      - redis-service

  celery-service:
    build:
      context: .
      dockerfile: Dockerfile-celery
    depends_on:
      - redis-service
      - kafka-service
      - zookeeper-service

  redis-service:
    image: redis
    ports:
      - "6379:6379"

  zookeeper-service:
    image: zookeeper
    ports:
      - "2181:2181"

  kafka-service:
    image: confluentinc/cp-kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper-service:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT_INTERNAL:PLAINTEXT,PLAINTEXT_EXTERNAL:PLAINTEXT
      KAFKA_LISTENERS: PLAINTEXT_INTERNAL://kafka-service:29092,PLAINTEXT_EXTERNAL://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT_INTERNAL://kafka-service:29092,PLAINTEXT_EXTERNAL://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT_INTERNAL
    depends_on:
      - zookeeper-service

networks:
  default:
    external:
      name: kafka-network
