FROM python:3.9-slim

WORKDIR /usr/src/app

COPY . .

RUN pip install --no-cache-dir -r flask_app/requirements.txt

RUN pip install --no-cache-dir -r app/requirements.txt


CMD ["celery", "-A", "run.celery", "worker", "--concurrency=16", "--pool=eventlet", "--loglevel=info"]
